### ISSUE TITLE
docker service failure with error 'ERROR: DockerService is not a class'

### ISSUE THREAD

**Issue by avinashkolluru** [someara/chef-docker#525]
I have a simple recipe which does:

```
docker_service 'default' do
  		action [:create, :start]
	end
```

I see the following error:

```
Generated at 2015-10-20 13:13:41 +0000
TypeError: DockerService is not a class
/var/chef/cache/cookbooks/docker/libraries/provider_docker_service.rb:3:in `<class:Provider>'
/var/chef/cache/cookbooks/docker/libraries/provider_docker_service.rb:2:in `<class:Chef>'
/var/chef/cache/cookbooks/docker/libraries/provider_docker_service.rb:1:in `<top (required)>'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:191:in `load'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:191:in `block in load_libraries_from_cookbook'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:188:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:188:in `load_libraries_from_cookbook'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:99:in `block in compile_libraries'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:98:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:71:in `compile'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:97:in `load'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:486:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:266:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/bin/chef-client:55:in `load'
/bin/chef-client:55:in `<main>'
```

**Comment by someara** [comment]
What version of chef-client ?

**Comment by avinashkolluru** [comment]
@someara 
Chef Client, version 12.4.1

**Comment by someara** [comment]
Did you put an "include 'docker'" in your metadata.rb?

**Comment by avinashkolluru** [comment]
depends 'docker', '= 2.1.2'

**Comment by someara** [comment]
The code in your stack trace is from the old (1.0.x) version of the cookbook.

Try cleaning your chef-client cache

-s

**Comment by avinashkolluru** [comment]
@someara 
Dont think so. Because the following file 
/var/chef/cache/cookbooks/docker/CHANGELOG.md has the following content

```
v2.1.2
--------------------
- Adding why_run support

v2.1.1
--------------------
#511 - fix container wait state checking
#512 - wait for registry ports to be open in test recipe
#519 - updating README to include labels#511 - fix container
...
```

**Comment by chasebolt** [comment]
chef-client -l debug will tell you at the top when it syncs cookbooks what
version it is going to use

**Comment by avinashkolluru** [comment]
Loading cookbooks [actionsaas@0.1.2, docker@2.1.2, compat_resource@12.5.9, zookeeper-cluster@1.1.2, java@1.35.0, libartifact@1.3.3, libarchive@0.6.1, apt@2.8.2, yum-epel@0.6.3, yum@3.8.1, poise@2.4.0, poise-service@1.0.2, selinux@0.9.0, mesos@3.4.0, chef-sugar@3.1.1, marathon@1.0.2, runit@1.7.4, packagecloud@0.1.0, zookeeper@1.6.1, build-essential@2.2.4, consul@1.2.0, chef-vault@1.3.1, chocolatey@0.4.1, windows@1.38.2, chef_handler@1.2.0, golang@1.7.0, firewall@1.6.1]

**Comment by someara** [comment]
This smells like a bug in chef-client. 

It is definitely the old code in the stack-trace.
provider_docker_service.rb no longer exists in 2.x, and it no longer uses LWRPBase.

Are you using a chef-server?

-s

**Comment by avinashkolluru** [comment]
@someara 
figured out the problem. this is a chef screwup.
I had 2 versions of the docker cookbook locally. When i uploaded using knife, it merged the files from both the cookbooks and uploaded them as the latest version on chef server.
I cleanup my local box, chef server and did a fresh upload. Things are fine now.

**Comment by someara** [comment]
That shouldn't have happened. Can you file a bug against chef-server, then
paste the link into this thread?

That way, people that find this via google can follow it.

-s

**Comment by avinashkolluru** [comment]
Filed issue - https://github.com/chef/chef/issues/4077

**Comment by someara** [comment]
Thanks Avinash!
